
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - laike9m.cyberbrain
    - ms-python.python
    - kevinrose.vsc-python-indent
    - jeff-hykin.better-dockerfile-syntax
    - github.vscode-pull-request-github
    - eamodio.gitlens
